import { LeadAttribution, SidebarNavLinkType } from '@/utils/types'
import { FaMicroblog } from 'react-icons/fa'
import { BiSolidOffer, BiSolidReport } from 'react-icons/bi'
import { SiGoogleadsense, SiGoogleads } from 'react-icons/si'
import { MdDashboard } from 'react-icons/md'
import ProfileIcon from '@/assets/Images/image.png'

// 1 -  For Sidebar
export const navLinks: SidebarNavLinkType[] = [
  {
    name: 'Dashboard',
    to: '/admin/dashboard',
    icon: <MdDashboard size={20} />,
  },
  {
    name: 'Blogs',
    to: '/admin/blogs',
    icon: <FaMicroblog size={20} />,
  },
  {
    name: 'Lender Offers',
    to: '/admin/lender-offers',
    icon: <BiSolidOffer size={20} />,
  },
  {
    name: 'Leads',
    to: '/admin/leads-managment',
    icon: <SiGoogleadsense size={20} />,
  },
  {
    name: 'Leads Reporting ',
    to: '/admin/leads-reporting',
    icon: <BiSolidReport size={20} />,
  },
  {
    name: 'HELOC Leads',
    to: '/admin/heloc-leads',
    icon: <SiGoogleads size={20} />,
  },
]

// 2 -  data for blog page
export const blogsData = [
  {
    title: 'John Doe',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-01-15',
  },
  {
    title: 'Jane Smith',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-02-21',
  },
  {
    title: 'Mike Johnson',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-03-10',
  },
  {
    title: 'Sarah Williams',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-04-05',
  },
  {
    title: 'David Brown',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-05-18',
  },
  {
    title: 'Emily Davis',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-06-22',
  },
  {
    title: 'Robert Wilson',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-07-14',
  },
  {
    title: 'Lisa Moore',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-08-30',
  },
  {
    title: 'Thomas Taylor',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-09-11',
  },
  {
    title: 'Jennifer Anderson',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-10-25',
  },
  {
    title: 'Alex Martinez',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-11-19',
  },
  {
    title: 'Patricia Clark',
    content:
      'Mostly they seek to define what blogging is, what makes it so important.',
    image: ProfileIcon,
    publishDate: '2023-12-08',
  },
]

// 3 Lender Offers Data
import { LenderOffer } from '@/utils/types'

export const lenderOffersData: LenderOffer[] = [
  {
    id: '1',
    lenderName: 'FastCash Finance',
    interestRate: '7.2%',
    loanTerm: '36 months',
    eligibility: 'Minimum credit score of 650',
    ctaLink: 'https://fastcash.com/apply',
    expirationDate: '2025-12-31',
    status: 'Active',
  },
  {
    id: '2',
    lenderName: 'Secure Loans Co.',
    interestRate: '6.5%',
    loanTerm: '48 months',
    eligibility: 'Employed for 1+ year, 700+ credit score',
    ctaLink: 'https://secureloans.com/start',
    expirationDate: '2025-11-15',
    status: 'Inactive',
  },
  {
    id: '3',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
  {
    id: '4',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
  {
    id: '5',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
  {
    id: '6',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
  {
    id: '7',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
  {
    id: '8',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
  {
    id: '9',
    lenderName: 'QuickFunds',
    interestRate: '8.1%',
    loanTerm: '24 months',
    eligibility: 'Monthly income > $3000',
    ctaLink: 'https://quickfunds.com/apply-now',
    expirationDate: '2025-10-01',
    status: 'Active',
  },
]

// Leads Reporting
export const leadAttributionData: LeadAttribution[] = [
  {
    id: '1',
    lenderName: 'QuickCash Lending',
    lenderOfferId: 'QCL-001',
    clickDate: '2024-01-20',
    clickTime: '14:30:25',
    userIp: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    referrerUrl: 'https://example.com/deal-analyzer',
    leadSource: 'Deal Analyzer',
    conversionStatus: 'Converted',
    leadValue: 2500,
    leadEmail: 'john.doe@email.com',
    leadPhone: '+1 (555) 123-4567',
    sessionId: 'ses_abc123',
    deviceType: 'Desktop',
    location: 'Austin, TX',
  },
  {
    id: '2',
    lenderName: 'FastTrack Finance',
    lenderOfferId: 'FTF-002',
    clickDate: '2024-01-20',
    clickTime: '16:45:12',
    userIp: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X)',
    referrerUrl: 'https://example.com/lender-comparison',
    leadSource: 'Lender Comparison',
    conversionStatus: 'Pending',
    sessionId: 'ses_def456',
    deviceType: 'Mobile',
    location: 'Dallas, TX',
  },
  {
    id: '3',
    lenderName: 'Prime Capital',
    lenderOfferId: 'PC-003',
    clickDate: '2024-01-19',
    clickTime: '10:15:33',
    userIp: '192.168.1.102',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    referrerUrl: 'https://example.com/homepage',
    leadSource: 'Homepage',
    conversionStatus: 'Converted',
    leadValue: 3200,
    leadEmail: 'sarah.smith@gmail.com',
    leadPhone: '+1 (555) 234-5678',
    sessionId: 'ses_ghi789',
    deviceType: 'Desktop',
    location: 'Houston, TX',
  },
  {
    id: '4',
    lenderName: 'QuickCash Lending',
    lenderOfferId: 'QCL-001',
    clickDate: '2024-01-19',
    clickTime: '09:22:45',
    userIp: '192.168.1.103',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    referrerUrl: 'https://google.com',
    leadSource: 'Organic Search',
    conversionStatus: 'Rejected',
    sessionId: 'ses_jkl012',
    deviceType: 'Desktop',
    location: 'San Antonio, TX',
  },
  {
    id: '5',
    lenderName: 'Secure Lending Co',
    lenderOfferId: 'SLC-004',
    clickDate: '2024-01-18',
    clickTime: '13:55:18',
    userIp: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X)',
    referrerUrl: 'https://example.com/blog',
    leadSource: 'Blog',
    conversionStatus: 'Converted',
    leadValue: 1800,
    leadEmail: 'mike.wilson@yahoo.com',
    leadPhone: '+1 (555) 345-6789',
    sessionId: 'ses_mno345',
    deviceType: 'Tablet',
    location: 'Fort Worth, TX',
  },
  {
    id: '6',
    lenderName: 'FastTrack Finance',
    lenderOfferId: 'FTF-002',
    clickDate: '2024-01-18',
    clickTime: '11:30:55',
    userIp: '192.168.1.105',
    userAgent: 'Mozilla/5.0 (Android 11; Mobile; rv:68.0)',
    leadSource: 'Direct Traffic',
    conversionStatus: 'Pending',
    sessionId: 'ses_pqr678',
    deviceType: 'Mobile',
    location: 'El Paso, TX',
  },
  {
    id: '7',
    lenderName: 'Prime Capital',
    lenderOfferId: 'PC-003',
    clickDate: '2024-01-17',
    clickTime: '15:12:30',
    userIp: '192.168.1.106',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    referrerUrl: 'https://facebook.com',
    leadSource: 'Social Media',
    conversionStatus: 'Converted',
    leadValue: 2900,
    leadEmail: 'lisa.brown@hotmail.com',
    leadPhone: '+1 (555) 456-7890',
    sessionId: 'ses_stu901',
    deviceType: 'Desktop',
    location: 'Plano, TX',
  },
  {
    id: '8',
    lenderName: 'Reliable Loans',
    lenderOfferId: 'RL-005',
    clickDate: '2024-01-17',
    clickTime: '08:45:22',
    userIp: '192.168.1.107',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)',
    referrerUrl: 'https://example.com/deal-analyzer',
    leadSource: 'Deal Analyzer',
    conversionStatus: 'Converted',
    leadValue: 4100,
    leadEmail: 'david.jones@email.com',
    leadPhone: '+1 (555) 567-8901',
    sessionId: 'ses_vwx234',
    deviceType: 'Mobile',
    location: 'Arlington, TX',
  },
  {
    id: '9',
    lenderName: 'QuickCash Lending',
    lenderOfferId: 'QCL-001',
    clickDate: '2024-01-16',
    clickTime: '12:20:15',
    userIp: '192.168.1.108',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    leadSource: 'Email Campaign',
    conversionStatus: 'Pending',
    sessionId: 'ses_yz567',
    deviceType: 'Desktop',
    location: 'Irving, TX',
  },
  {
    id: '10',
    lenderName: 'Secure Lending Co',
    lenderOfferId: 'SLC-004',
    clickDate: '2024-01-16',
    clickTime: '17:35:40',
    userIp: '192.168.1.109',
    userAgent: 'Mozilla/5.0 (Android 12; Mobile; rv:91.0)',
    referrerUrl: 'https://example.com/lender-comparison',
    leadSource: 'Lender Comparison',
    conversionStatus: 'Rejected',
    sessionId: 'ses_abc890',
    deviceType: 'Mobile',
    location: 'Garland, TX',
  },
]
